#include <Adafruit_NeoPixel.h>
#include <EEPROM.h>

#ifndef LED_COUNT
#define LED_COUNT 116
#endif
#define LED_PIN 6
#define BUZZER_PIN 7
#define PLAY_PAUSE_BUTTON_PIN 5
#define NEXT_STAGE_BUTTON_PIN 4
#define BAUD_RATE 115200
#define PROTOCOL_VERSION 3
#define RX_BUFFER_SIZE 336
#define BUTTON_DEBOUNCE_MS 35
#define LONG_PRESS_MS 3000
#define CONTROL_LEASE_MS 3000
#define SERIAL_ACQUIRE_QUIET_MS 300
#define BLINK_FADE_MS 700
#define LED_FRAME_INTERVAL_MS 16
#define BUZZER_INTERVAL_MS 1500
#define BUZZER_DURATION_MS 75
#define PRESET_MAGIC 0x544C5053UL
#define PRESET_SCHEMA 1
#define MAX_STAGES 5
#define BUZZ_EVENT_SLOTS 4

Adafruit_NeoPixel pixel(LED_COUNT, LED_PIN, NEO_GRB + NEO_KHZ800);
char inputBuffer[RX_BUFFER_SIZE]; uint16_t inputLength = 0; bool inputOverflow = false;
enum LedEffect { EFFECT_OFF, EFFECT_SOLID, EFFECT_BLINK };
enum BuzzerMode { BUZZER_NONE, BUZZER_ONCE, BUZZER_REPEAT };
enum TimerState { TIMER_IDLE, TIMER_RUNNING, TIMER_PAUSED };
struct __attribute__((packed)) StoredStage { uint32_t threshold; uint32_t color; uint8_t flags; };
struct __attribute__((packed)) StoredPreset { uint32_t magic; uint32_t sequence; uint8_t schema; uint8_t stageCount; uint32_t duration; StoredStage stages[MAX_STAGES]; uint16_t checksum; };
StoredPreset preset; uint8_t activeSlot = 0; TimerState timerState = TIMER_IDLE; uint8_t standaloneStage = 0; uint32_t accumulatedMs = 0, runStartedMillis = 0;
uint32_t desiredColor = 0, displayedColor = 0, transitionStartColor = 0, transitionTargetColor = 0, transitionElapsed = 0, blinkElapsed = 0, lastAnimationMillis = 0, lastLedFrameMillis = 0, nextBuzzerMillis = 0;
uint16_t transitionDuration = 0; LedEffect ledEffect = EFFECT_OFF; bool animationPlaying = false; BuzzerMode buzzerMode = BUZZER_NONE;
uint32_t appliedRevision = 0, buttonSequence = 0, browserLeaseExpires = 0, lastSerialActivityMillis = 0, browserSessionHash = 0, lastStoreRequestHash = 0, buzzEventHashes[BUZZ_EVENT_SLOTS] = {}; bool serialActivitySeen = false; uint8_t buzzEventCount = 0;
struct ButtonState { uint8_t pin; bool lastReading; bool stableReading; uint32_t changedAt; uint32_t pressedAt; bool longReported; };
ButtonState playPauseButton = { PLAY_PAUSE_BUTTON_PIN, HIGH, HIGH, 0, 0, false }, nextStageButton = { NEXT_STAGE_BUTTON_PIN, HIGH, HIGH, 0, 0, false };
struct Span { const char* begin; const char* end; };

void skipWhitespace(const char*& p, const char* end) { while (p < end && (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n')) p++; }
bool sameText(const char* p, size_t length, const char* expected) { return length == strlen(expected) && !strncmp(p, expected, length); }
bool valueSpan(Span input, Span& output) {
  const char* p = input.begin; skipWhitespace(p, input.end); if (p >= input.end) return false; const char* start = p;
  if (*p == '"') { p++; bool escaped = false; while (p < input.end) { char c = *p++; if (escaped) escaped = false; else if (c == '\\') escaped = true; else if (c == '"') { output = { start, p }; return true; } } return false; }
  if (*p == '[' || *p == '{') { char open = *p, close = open == '[' ? ']' : '}'; uint8_t depth = 0; bool quoted = false, escaped = false; while (p < input.end) { char c = *p++; if (quoted) { if (escaped) escaped = false; else if (c == '\\') escaped = true; else if (c == '"') quoted = false; } else if (c == '"') quoted = true; else if (c == open) depth++; else if (c == close && --depth == 0) { output = { start, p }; return true; } } return false; }
  while (p < input.end && *p != ',' && *p != '}' && *p != ']' && *p != ' ' && *p != '\t' && *p != '\r' && *p != '\n') p++; output = { start, p }; return p != start;
}
bool findKey(Span object, const char* key, Span& value) { const char* p = object.begin; while (p < object.end) { if (*p++ != '"') continue; const char* start = p; bool escaped = false; while (p < object.end) { if (escaped) escaped = false; else if (*p == '\\') escaped = true; else if (*p == '"') break; p++; } if (p >= object.end) return false; const char* after = p + 1; skipWhitespace(after, object.end); if (after < object.end && *after == ':' && sameText(start, p - start, key)) return valueSpan({ after + 1, object.end }, value); p++; } return false; }
bool readJsonString(Span value, char* output, size_t size) { if (value.begin >= value.end || *value.begin != '"' || value.end[-1] != '"' || !size) return false; const char* p = value.begin + 1; size_t length = 0; while (p < value.end - 1) { char c = *p++; if (c == '\\' && p < value.end - 1) c = *p++; if (length + 1 >= size) return false; output[length++] = c; } output[length] = 0; return true; }
bool readText(Span object, const char* key, char* output, size_t size) { Span value; return findKey(object, key, value) && readJsonString(value, output, size); }
bool readUnsigned(Span value, uint32_t& output) { const char* p = value.begin; skipWhitespace(p, value.end); uint32_t result = 0; bool digit = false; while (p < value.end && *p >= '0' && *p <= '9') { digit = true; uint8_t n = *p++ - '0'; if (result > (0xFFFFFFFFUL - n) / 10) return false; result = result * 10 + n; } skipWhitespace(p, value.end); output = result; return digit && p == value.end; }
bool readBoolean(Span value, bool& output) { if (sameText(value.begin, value.end - value.begin, "true")) { output = true; return true; } if (sameText(value.begin, value.end - value.begin, "false")) { output = false; return true; } return false; }
bool readColor(Span value, uint32_t& output) { char text[8]; if (!readJsonString(value, text, sizeof(text)) || text[0] != '#' || strlen(text) != 7) return false; output = 0; for (uint8_t i = 1; i < 7; i++) { char c = text[i]; uint8_t n = c >= '0' && c <= '9' ? c - '0' : c >= 'a' && c <= 'f' ? c - 'a' + 10 : c >= 'A' && c <= 'F' ? c - 'A' + 10 : 255; if (n == 255) return false; output = output << 4 | n; } return true; }
uint32_t textHash(const char* value) { uint32_t hash = 2166136261UL; while (*value) { hash ^= (uint8_t)*value++; hash *= 16777619UL; } return hash ? hash : 1; }
bool sessionMatches(Span object) { char session[41]; return readText(object, "sessionId", session, sizeof(session)) && browserSessionHash && textHash(session) == browserSessionHash; }

uint16_t checksum(const StoredPreset& value) { const uint8_t* bytes = (const uint8_t*)&value; uint16_t result = 0xFFFF; for (size_t i = 0; i < offsetof(StoredPreset, checksum); i++) { result ^= bytes[i]; for (uint8_t bit = 0; bit < 8; bit++) result = result & 1 ? result >> 1 ^ 0xA001 : result >> 1; } return result; }
bool validPreset(const StoredPreset& value) { if (value.magic != PRESET_MAGIC || value.schema != PRESET_SCHEMA || value.stageCount < 3 || value.stageCount > MAX_STAGES || !value.duration || value.checksum != checksum(value)) return false; for (uint8_t i = 0; i < value.stageCount; i++) if (value.stages[i].threshold >= value.duration || (i && value.stages[i].threshold <= value.stages[i - 1].threshold) || (value.stages[i].flags & 3) > BUZZER_REPEAT) return false; return true; }
void compiledDefault() { memset(&preset, 0, sizeof(preset)); preset.magic = PRESET_MAGIC; preset.schema = PRESET_SCHEMA; preset.stageCount = 4; preset.duration = 240; uint32_t times[] = {0,60,120,180}, colors[] = {0x0000FF,0xFFFF00,0xFF7B00,0xFF0000}; for (uint8_t i = 0; i < 4; i++) { preset.stages[i].threshold = times[i]; preset.stages[i].color = colors[i]; preset.stages[i].flags = i == 0 ? BUZZER_NONE : i == 3 ? BUZZER_REPEAT : BUZZER_ONCE; } preset.checksum = checksum(preset); }
void loadPreset() { StoredPreset slots[2]; EEPROM.get(0, slots[0]); EEPROM.get(sizeof(StoredPreset), slots[1]); bool a = validPreset(slots[0]), b = validPreset(slots[1]); if (!a && !b) { compiledDefault(); return; } activeSlot = b && (!a || (int32_t)(slots[1].sequence - slots[0].sequence) > 0); preset = slots[activeSlot]; }
void persistPreset() { uint8_t target = activeSlot ^ 1; int base = target * sizeof(StoredPreset); preset.magic = PRESET_MAGIC; preset.schema = PRESET_SCHEMA; preset.sequence++; preset.checksum = checksum(preset); uint32_t invalid = 0; EEPROM.put(base, invalid); const uint8_t* bytes = (const uint8_t*)&preset; for (size_t i = 4; i < sizeof(preset); i++) EEPROM.update(base + i, bytes[i]); for (uint8_t i = 0; i < 4; i++) EEPROM.update(base + i, bytes[i]); activeSlot = target; }

void printJsonString(const char* value) { Serial.print('"'); while (*value) { if (*value == '"' || *value == '\\') Serial.print('\\'); Serial.print(*value++); } Serial.print('"'); }
void sendError(const char* message, const char* id = 0) { Serial.print(F("{\"version\":3,\"type\":\"error\"")); if (id && id[0]) { Serial.print(F(",\"requestId\":")); printJsonString(id); } Serial.print(F(",\"message\":")); printJsonString(message); Serial.println('}'); }
void sendAck(const char* id) { Serial.print(F("{\"version\":3,\"type\":\"ack\",\"requestId\":")); printJsonString(id); Serial.print(F(",\"appliedRevision\":")); Serial.print(appliedRevision); Serial.println('}'); }
void sendReady(const char* id = 0) { Serial.print(F("{\"version\":3,\"type\":\"ready\"")); if (id && id[0]) { Serial.print(F(",\"requestId\":")); printJsonString(id); } Serial.print(F(",\"device\":\"timelight-arduino\",\"firmware\":\"0.4.0\",\"ledCount\":")); Serial.print(LED_COUNT); Serial.println(F(",\"buttons\":[\"play_pause\",\"next_stage\",\"reset\"],\"capabilities\":[\"standalone-preset\"]}")); }
void sendButton(const char* name) { Serial.print(F("{\"version\":3,\"type\":\"button\",\"button\":")); printJsonString(name); Serial.print(F(",\"sequence\":")); Serial.print(++buttonSequence); Serial.println('}'); }

void setStripColor(uint32_t color) { uint32_t value = pixel.Color(color >> 16 & 255, color >> 8 & 255, color & 255); for (uint16_t i = 0; i < LED_COUNT; i++) pixel.setPixelColor(i, value); pixel.show(); displayedColor = color; lastLedFrameMillis = millis(); }
uint8_t blend(uint8_t from, uint8_t to, uint32_t elapsed, uint16_t duration) { if (!duration || elapsed >= duration) return to; int32_t difference = (int32_t)to - from; return (uint8_t)((int32_t)from + difference * (int32_t)elapsed / duration); }
uint32_t scaleColor(uint32_t color, uint8_t brightness) { return (uint32_t)(color >> 16 & 255) * brightness / 255 << 16 | (uint32_t)(color >> 8 & 255) * brightness / 255 << 8 | (color & 255) * brightness / 255; }
uint32_t renderedColor() { uint32_t color = transitionDuration && transitionElapsed < transitionDuration ? (uint32_t)blend(transitionStartColor >> 16, transitionTargetColor >> 16, transitionElapsed, transitionDuration) << 16 | (uint32_t)blend(transitionStartColor >> 8, transitionTargetColor >> 8, transitionElapsed, transitionDuration) << 8 | blend(transitionStartColor, transitionTargetColor, transitionElapsed, transitionDuration) : desiredColor; if (ledEffect == EFFECT_OFF) return 0; if (ledEffect == EFFECT_BLINK && (!transitionDuration || transitionElapsed >= transitionDuration)) { uint32_t phase = blinkElapsed; uint8_t brightness = phase < BLINK_FADE_MS ? 255 - phase * 255 / BLINK_FADE_MS : (phase - BLINK_FADE_MS) * 255 / BLINK_FADE_MS; return scaleColor(desiredColor, brightness); } return color; }
void updateLeds() { uint32_t now = millis(), delta = now - lastAnimationMillis; lastAnimationMillis = now; if (animationPlaying) { if (transitionDuration && transitionElapsed < transitionDuration) transitionElapsed = min((uint32_t)transitionDuration, transitionElapsed + delta); else if (ledEffect == EFFECT_BLINK) blinkElapsed = (blinkElapsed + delta) % (BLINK_FADE_MS * 2UL); } uint32_t color = renderedColor(); if (!browserSessionHash && serialActivitySeen && now - lastSerialActivityMillis < SERIAL_ACQUIRE_QUIET_MS) return; if (now - lastLedFrameMillis >= LED_FRAME_INTERVAL_MS && color != displayedColor) setStripColor(color); }
void applyOutputs(uint32_t color, LedEffect effect, uint16_t transition, bool playing, BuzzerMode buzzer) { bool changed = effect != ledEffect || color != desiredColor; if (effect == EFFECT_OFF) { desiredColor = 0; ledEffect = EFFECT_OFF; transitionDuration = transitionElapsed = blinkElapsed = 0; animationPlaying = false; setStripColor(0); } else { if (changed) { transitionStartColor = renderedColor(); desiredColor = transitionTargetColor = color; transitionDuration = transition; transitionElapsed = blinkElapsed = 0; } ledEffect = effect; animationPlaying = playing; } lastAnimationMillis = millis(); buzzerMode = buzzer; nextBuzzerMillis = 0; if (buzzer != BUZZER_REPEAT) noTone(BUZZER_PIN); updateLeds(); }
void updateBuzzer() { if (buzzerMode != BUZZER_REPEAT) return; uint32_t now = millis(); if (!nextBuzzerMillis || (int32_t)(now - nextBuzzerMillis) >= 0) { tone(BUZZER_PIN, 2400, BUZZER_DURATION_MS); nextBuzzerMillis = now + BUZZER_INTERVAL_MS; } }

void stopTimerAndOutputs() { timerState = TIMER_IDLE; accumulatedMs = 0; standaloneStage = 0; applyOutputs(0, EFFECT_OFF, 0, false, BUZZER_NONE); }
uint32_t standaloneElapsed() { return accumulatedMs + (timerState == TIMER_RUNNING ? millis() - runStartedMillis : 0); }
void showStage(uint8_t index, bool alert) { StoredStage& stage = preset.stages[index]; BuzzerMode sound = (BuzzerMode)(stage.flags & 3); applyOutputs(stage.color, stage.flags & 4 ? EFFECT_BLINK : EFFECT_SOLID, 0, timerState == TIMER_RUNNING, timerState == TIMER_RUNNING && sound == BUZZER_REPEAT ? BUZZER_REPEAT : BUZZER_NONE); if (alert && timerState == TIMER_RUNNING && sound == BUZZER_ONCE) tone(BUZZER_PIN, 2400, BUZZER_DURATION_MS); }
void toggleStandalone() { if (timerState == TIMER_IDLE) { timerState = TIMER_RUNNING; accumulatedMs = 0; runStartedMillis = millis(); standaloneStage = 0; showStage(0, false); } else if (timerState == TIMER_RUNNING) { accumulatedMs = standaloneElapsed(); timerState = TIMER_PAUSED; animationPlaying = false; buzzerMode = BUZZER_NONE; noTone(BUZZER_PIN); } else { timerState = TIMER_RUNNING; runStartedMillis = millis(); animationPlaying = true; buzzerMode = (preset.stages[standaloneStage].flags & 3) == BUZZER_REPEAT ? BUZZER_REPEAT : BUZZER_NONE; nextBuzzerMillis = 0; } }
void nextStandalone() { if (timerState == TIMER_IDLE || standaloneStage + 1 >= preset.stageCount) return; standaloneStage++; accumulatedMs = preset.stages[standaloneStage].threshold * 1000UL; if (timerState == TIMER_RUNNING) runStartedMillis = millis(); showStage(standaloneStage, timerState == TIMER_RUNNING); }
void updateStandalone() { if (timerState != TIMER_RUNNING) return; uint32_t elapsed = standaloneElapsed(); uint8_t stage = standaloneStage; while (stage + 1 < preset.stageCount && elapsed >= preset.stages[stage + 1].threshold * 1000UL) stage++; if (stage != standaloneStage) { standaloneStage = stage; showStage(stage, true); } }
void renewLease() { browserLeaseExpires = millis() + CONTROL_LEASE_MS; }
void acquireBrowser(const char* session) { stopTimerAndOutputs(); uint32_t hash = textHash(session); if (browserSessionHash != hash) { browserSessionHash = hash; appliedRevision = 0; buzzEventCount = 0; lastStoreRequestHash = 0; } renewLease(); }
void releaseBrowser(bool announce) { if (!browserSessionHash) return; browserSessionHash = 0; browserLeaseExpires = 0; stopTimerAndOutputs(); if (announce) sendReady(); }
bool rememberBuzz(const char* id) { uint32_t hash = textHash(id); for (uint8_t i = 0; i < buzzEventCount; i++) if (buzzEventHashes[i] == hash) return false; if (buzzEventCount < BUZZ_EVENT_SLOTS) buzzEventHashes[buzzEventCount++] = hash; else { for (uint8_t i = 1; i < BUZZ_EVENT_SLOTS; i++) buzzEventHashes[i - 1] = buzzEventHashes[i]; buzzEventHashes[BUZZ_EVENT_SLOTS - 1] = hash; } return true; }
bool nextArrayValue(Span array, const char*& p, Span& value) { skipWhitespace(p, array.end); if (p == array.begin && p < array.end && *p == '[') { p++; skipWhitespace(p, array.end); } if (p < array.end && *p == ',') { p++; skipWhitespace(p, array.end); } if (p >= array.end || *p == ']') return false; if (!valueSpan({p,array.end}, value)) return false; p = value.end; return true; }
bool parsePreset(Span message, StoredPreset& result) { Span field, list; uint32_t duration; if (!findKey(message, "duration", field) || !readUnsigned(field, duration) || !duration || duration > 86400 || !findKey(message, "stages", list) || *list.begin != '[') return false; result = preset; memset(result.stages, 0, sizeof(result.stages)); result.duration = duration; result.stageCount = 0; const char* p = list.begin + 1; while (p < list.end - 1) { skipWhitespace(p, list.end); if (*p == ',') { p++; continue; } if (*p == ']') break; Span stage; if (!valueSpan({p,list.end}, stage) || *stage.begin != '[' || result.stageCount >= MAX_STAGES) return false; const char* item = stage.begin; Span thresholdValue, colorValue, blinkValue, buzzerValue; uint32_t threshold, color; bool blink; char buzzer[8]; if (!nextArrayValue(stage,item,thresholdValue) || !nextArrayValue(stage,item,colorValue) || !nextArrayValue(stage,item,blinkValue) || !nextArrayValue(stage,item,buzzerValue) || !readUnsigned(thresholdValue,threshold) || !readColor(colorValue,color) || !readBoolean(blinkValue,blink) || !readJsonString(buzzerValue,buzzer,sizeof(buzzer))) return false; skipWhitespace(item, stage.end); if (item >= stage.end || *item != ']') return false; uint8_t mode = !strcmp(buzzer,"none") ? BUZZER_NONE : !strcmp(buzzer,"once") ? BUZZER_ONCE : !strcmp(buzzer,"repeat") ? BUZZER_REPEAT : 255; if (mode == 255 || threshold >= duration || (result.stageCount && threshold <= result.stages[result.stageCount-1].threshold)) return false; StoredStage& out = result.stages[result.stageCount++]; out.threshold = threshold; out.color = color; out.flags = mode | (blink ? 4 : 0); p = stage.end; } return result.stageCount >= 3; }

void handleMessage() {
  inputBuffer[inputLength] = 0; Span message = {inputBuffer,inputBuffer+inputLength}, value; char id[41] = "", type[20]; uint32_t version; readText(message,"requestId",id,sizeof(id)); if (!findKey(message,"version",value) || !readUnsigned(value,version) || version != PROTOCOL_VERSION) { sendError("Unsupported protocol version",id); return; } if (!readText(message,"type",type,sizeof(type))) { sendError("Missing message type",id); return; }
  if (!strcmp(type,"hello")) { char session[41]; if (!readText(message,"sessionId",session,sizeof(session))) { sendError("Invalid browser session",id); return; } acquireBrowser(session); sendReady(id); return; }
  if (!strcmp(type,"ping")) { Serial.print(F("{\"version\":3,\"type\":\"pong\",\"requestId\":")); printJsonString(id); Serial.println('}'); sendAck(id); return; }
  if (!strcmp(type,"release_control")) { if (!sessionMatches(message)) { sendError("Unknown browser session",id); return; } sendAck(id); releaseBrowser(false); return; }
  if (!sessionMatches(message)) { sendError("Unknown browser session",id); return; } renewLease();
  if (!strcmp(type,"keepalive")) { sendAck(id); return; }
  if (!strcmp(type,"store_preset")) { uint32_t requestHash = textHash(id); if (id[0] && requestHash == lastStoreRequestHash) { sendAck(id); return; } StoredPreset candidate; if (!parsePreset(message,candidate)) { sendError("Invalid standalone preset",id); return; } preset = candidate; persistPreset(); timerState = TIMER_IDLE; accumulatedMs = 0; lastStoreRequestHash = requestHash; sendAck(id); return; }
  if (!strcmp(type,"buzz_once")) { char event[41]; if (!readText(message,"eventId",event,sizeof(event))) { sendError("Invalid buzzer event",id); return; } if (rememberBuzz(event)) tone(BUZZER_PIN,2400,BUZZER_DURATION_MS); sendAck(id); return; }
  if (!strcmp(type,"set_outputs")) { uint32_t revision, transition, lease, color; char effect[10], animation[10], buzzer[10]; if (!findKey(message,"revision",value)||!readUnsigned(value,revision)||!findKey(message,"color",value)||!readColor(value,color)||!readText(message,"ledEffect",effect,sizeof(effect))||!findKey(message,"transitionMs",value)||!readUnsigned(value,transition)||transition>5000||!readText(message,"animationState",animation,sizeof(animation))||!readText(message,"buzzerMode",buzzer,sizeof(buzzer))||!findKey(message,"leaseMs",value)||!readUnsigned(value,lease)||lease>3000) { sendError("Invalid output snapshot",id); return; } LedEffect e=!strcmp(effect,"off")?EFFECT_OFF:!strcmp(effect,"solid")?EFFECT_SOLID:!strcmp(effect,"blink")?EFFECT_BLINK:(LedEffect)255; BuzzerMode b=!strcmp(buzzer,"none")?BUZZER_NONE:!strcmp(buzzer,"repeat")?BUZZER_REPEAT:(BuzzerMode)255; if(e==(LedEffect)255||b==(BuzzerMode)255||(strcmp(animation,"playing")&&strcmp(animation,"paused"))){sendError("Invalid output effect or animation state",id);return;} if(revision>appliedRevision){appliedRevision=revision;applyOutputs(color,e,transition,!strcmp(animation,"playing"),b);} sendAck(id); return; }
  sendError("Unsupported command",id);
}
void readSerial(){while(Serial.available()){char c=Serial.read();lastSerialActivityMillis=millis();serialActivitySeen=true;if(c=='\r')continue;if(c=='\n'){if(inputOverflow)sendError("Message too long");else if(inputLength)handleMessage();inputLength=0;inputOverflow=false;}else if(inputLength+1>=RX_BUFFER_SIZE)inputOverflow=true;else inputBuffer[inputLength++]=c;}}
bool updateButton(ButtonState& b){bool reading=digitalRead(b.pin);uint32_t now=millis();if(reading!=b.lastReading){b.lastReading=reading;b.changedAt=now;}if(now-b.changedAt<BUTTON_DEBOUNCE_MS||reading==b.stableReading)return false;b.stableReading=reading;if(reading==LOW){b.pressedAt=now;b.longReported=false;}return true;}
void handleButtons(){bool play=updateButton(playPauseButton),next=updateButton(nextStageButton),owned=browserSessionHash;if(play&&playPauseButton.stableReading==HIGH){if(owned)sendButton("play_pause");else toggleStandalone();}if(nextStageButton.stableReading==LOW&&!nextStageButton.longReported&&millis()-nextStageButton.pressedAt>=LONG_PRESS_MS){nextStageButton.longReported=true;if(owned)sendButton("reset");else stopTimerAndOutputs();}if(next&&nextStageButton.stableReading==HIGH&&!nextStageButton.longReported){if(owned)sendButton("next_stage");else nextStandalone();}}
void setup(){pinMode(BUZZER_PIN,OUTPUT);pinMode(PLAY_PAUSE_BUTTON_PIN,INPUT_PULLUP);pinMode(NEXT_STAGE_BUTTON_PIN,INPUT_PULLUP);playPauseButton.lastReading=playPauseButton.stableReading=digitalRead(PLAY_PAUSE_BUTTON_PIN);nextStageButton.lastReading=nextStageButton.stableReading=digitalRead(NEXT_STAGE_BUTTON_PIN);pixel.begin();pixel.setBrightness(80);pixel.clear();pixel.show();loadPreset();stopTimerAndOutputs();Serial.begin(BAUD_RATE);delay(50);sendReady();}
void loop(){readSerial();if(browserSessionHash&&(int32_t)(millis()-browserLeaseExpires)>=0)releaseBrowser(true);handleButtons();updateStandalone();updateLeds();updateBuzzer();}
